dist: focal

language: minimal

stages:
  - lint
  - test
  - deploy

if: branch = master OR type = pull_request

jobs:
  include:
    - stage: lint
      name: Project Syntax Verification
      script: make docker/run target=lint
    - stage: test
      name: Apply Terraform test configs in mockstack
      install: make mockstack/up
      script: make mockstack/pytest
      after_script: make mockstack/clean
    - stage: deploy
      if: branch = master AND type = push AND repo = plus3it/terraform-aws-tardigrade-security-group
      before_script:
        - |
          PRIOR_VERSION=$(git describe --abbrev=0 --tags)
          RELEASE_VERSION=$(grep current_version $TRAVIS_BUILD_DIR/.bumpversion.cfg | sed 's/^.*= //' )
          RELEASE_BODY="* [terraform-aws-tardigrade-security-group v$RELEASE_VERSION CHANGELOG](https://github.com/plus3it/terraform-aws-tardigrade-security-group/blob/$RELEASE_VERSION/CHANGELOG.md)"
          export PRIOR_VERSION RELEASE_VERSION RELEASE_BODY
      script: skip
      before_deploy:
        - |
          (set -x; git tag -a $RELEASE_VERSION -m $RELEASE_VERSION)
      deploy:
        provider: releases
        api_key:
          secure: NhR02a4cZFiWIKNvP9kZt+0LSdxDLzSrOEhlgfBJeO4YSbofvfDUPl9PP8mxeNoeCdyOUX6Pjk4TrMmwFKyJIoI226bOfXsqAnOcOg+p6Nh2SYz31kUFfU5NUGDOkuLK02F4XHTBVVU/eEHP03R5ZLlpPx/GafDMudUqkKZ0d5OtBrQR/HPeaefsNpLtnlxpOrF1WPkfIXkPfeyBiZvzlYxPQuQYxHTS19CjQn6KdzrYL14Nni9EwnUZYr7DoNYHeDXUJyKWQjIiIKGc27jqvOUPl1pCB36cwvA7ciOe7NvdptZ8LcE/Cq4gtyKXJ2wQVm1hBxRxH2Z+TkHo/1qsiPr6Xg19a8SNxh2AD5syG4eNte21G4eLUMmVKlUVB0w4lVHT2KqSLmEuCjHHEsblgGFy2OYVb40S88JlyI+CR+CqTLple3JO2witAuNghO5kB1PUuPgeYQ5MgPfbw4x9EpdwLNjDKridO/DqITADmyGMKVk2fSj5ZY/pP2b4lMZB0eEWzE5aBQFfDiTLM8tAyURE5FU6+IQsDAbhnipb6XGmuNFjyGwe6KH0cyzqkoGVjW+7MZoZclfRCegqXVp2i4Y5dstiKHEw9r3vYrPgXuIKPnxqm/nkKyGvL5FCtb+DpCGzhrLMZmq4y9kViLaJsmWJqaBAqjS9jAo4lCud+Xo=
        name: $RELEASE_VERSION
        body: $RELEASE_BODY
        tag_name: $RELEASE_VERSION
        target_commitish: $TRAVIS_COMMIT
        draft: false
        on:
          branch: master
          repo: plus3it/terraform-aws-tardigrade-security-group
          condition: '"$PRIOR_VERSION" != "$RELEASE_VERSION"'
